[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefer-offline --no-audit"

# Headers per performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache statico per immagini e assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache per pagine HTML
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Redirect www to non-www (SEO)
[[redirects]]
  from = "https://www.brix-ia.com/*"
  to = "https://brix-ia.com/:splat"
  status = 301
  force = true

# Redirect old paths (se necessario)
# [[redirects]]
#   from = "/old-path/*"
#   to = "/new-path/:splat"
#   status = 301

# Fallback per 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404
